fix: 1. run out of memory by kfac optimizer. 2. torch._C._LinAlgError
 Traceback:
1% ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33,536/3,000,000  [ 0:03:00 < 4:11:15 , 197 it/s ]
Traceback (most recent call last):
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\main.py", line 142, in <module>
    train(config)
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\main.py", line 42, in train
    model.learn(
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\zhao_2d\acktr\acktr.py", line 200, in learn
    return super().learn(
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\zhao_2d\common\on_policy_algorithm.py", line 345, in learn
    self.train()
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\zhao_2d\acktr\acktr.py", line 177, in train
    self.policy.optimizer.step()
  File "D:\anaconda3\envs\PyTroch\lib\site-packages\torch\optim\optimizer.py", line 484, in wrapper
    out = func(*args, **kwargs)
  File "c:\Users\USER\Desktop\DCNLab\experiments\Zhao-2D\zhao_2d\acktr\kfac.py", line 215, in step
    self.d_a[m], self.Q_a[m] = torch.linalg.eigh(
torch._C._LinAlgError: linalg.eigh: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 133082).
Exception in thread ChkStopThr:

Fix approach:
1. Split  `self.m_aa[m]`  and  `self.m_gg[m]` matrix into small block matrix, avoiding out of memory broblem when using `th.linalg.eigh`.
2. Doing regularization on the matrix  `self.m_aa[m]`  and  `self.m_gg[m]` passed to the `th.linalg.eigh` function by adding a small positive number to `self.m_aa[m]` and `self.m_gg[m]` during `optimizer.step()`.