fix: support cuda
Traceback:
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params,
jobz, uplo, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(W), CUDA_R_32F,
reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost),
workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you
may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See
https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

Fix approach:
change to another linalg library.
add `th.backends.cuda.preferred_linalg_library("magma")` in acktr.py.